"""Categorical polytope lecture — standalone, stdlib-only."""

from .cartesian_closed import curry_bijection, exponential
from .conceptual_polytope import (
    AdjunctionDirection,
    ConceptualPolytope,
    Vertex,
    maximize_under_coproduct_blocks,
)
from .fisher_pruned_search import FisherPrunedVertexSearch, NearOptimalProbeResult
from .formal_bounds import (
    TheoremConstants,
    certify_suboptimality,
    epsilon_0_explicit,
    theorem_constants_from_fisher,
)
from .coexponential_alternatives import CategoricalSetting, probe_setting
from .discoveries import Discovery, run_all_discoveries, write_discovery_artifacts
from .discoveries_research import run_research_discoveries
from .enriched_fisher import EnrichmentWeights, compare_epsilon_unweighted_vs_enriched
from .lawvere_metric import LawvereMetric, compare_lawvere_vs_plain
from .learner_diagram import (
    LearnerSession,
    LearnerTrajectoryLog,
    LiveEpsilonReading,
    SearchMode,
    TrajectoryStep,
    recommend_search_mode,
)
from .confusion_scorer import (
    ConfusionScorer,
    LEDGER,
    Proposition,
    Stance,
    TurnScore,
    detect_stance,
    score_dialogue,
    score_text,
)
from .presheaf_site import FiniteSite, default_two_object_site, sweep_site_exponentials
from .formal_proofs import (
    FormalStatement,
    PROOF_REGISTRY,
    formal_discoveries_markdown,
    verify_all_proofs,
)
from .firsts import deliverables_manifest, run_numerical_firsts
from .nonlinear_objective import (
    HypersurfacePlusInteraction,
    NonlinearAnalysis,
    NonlinearStudy,
    demonstrate_nonlinear,
    empirical_fisher_at,
    vertex_maximize,
)
from .decomposition_stability import (
    DecompositionStabilityReport,
    DecompositionStrategy,
    DesignRulebook,
    StabilityBounds,
    assess_decomposition,
    demonstrate_robustness,
    robustness_sweep,
    stability_framework_summary,
)
from .vertex_probe import (
    AlgorithmStep,
    NearOptimalProbe,
    StructuralReason,
    VertexProbeAlgorithm,
    VertexProbeCertificate,
    demonstrate_vertex_algorithm,
    vertex_reduction_argument,
)
from .extremal_substitute import (
    ExtremalSelectionResult,
    FormalCoexponentialSpec,
    SubstituteLimits,
    SubstituteReport,
    evaluate_substitute,
    extremal_selection_on_polytope,
    demonstrate_substitute,
    substitute_summary,
)
from .bridge_fisher_adversarial import factorization_from_hypersurface, fisher_from_coupled_problem
from .fisher_factorization import (
    BlockFisher,
    BlockLayout,
    FactorizationAnalysis,
    LeakageReport,
    QuadraticJointObjective,
    build_block_fisher,
    demonstrate_fisher_factorization,
    factorization_summary,
    nearly_optimal_when,
)
from .adversarial_probe import (
    BlockAssignment,
    ComponentwiseProbe,
    CoupledProblem,
    ParameterBlockSpec,
    WorstCaseResult,
    adversarial_theorem_summary,
    default_hypersurface_problem,
    demonstrate_adversarial,
)
from .hypersurface_box import (
    BoxBounds,
    CompositeObjective,
    HypersurfaceBox,
    MaximizerResult,
    Theta,
    box_theorem_summary,
    demonstrate_box,
)
from .neighboring_vertices import (
    NEIGHBOR_GUIDES,
    NeighborVertex,
    VertexGuide,
    closed_monoidal_vs_cartesian,
    demonstrate_neighbors,
    duality_strategy_note,
    walk_from_empty_coexponential,
)
from .set_category import (
    cardinality_obstruction,
    hom_cardinality,
    left_adjoint_to_coproduct_exists,
)
from .newton_tropical import (
    Monomial,
    NewtonFace,
    demonstrate_newton_tropical,
    newton_tropical_face,
    orthant_gap,
    sharp_gap_constant,
    sharp_single_axis_gap,
    tropical_exponent,
    tropical_gap_leading,
)
from .face_selection import (
    BasePower,
    EdgeCoordinateChart,
    FaceAnalysis,
    FaceSelectionProblem,
    FaceStatus,
    HypothesisStatus,
    InitialForm,
    LawHypotheses,
    PerturbationMonomial,
    PolynomialPerturbation,
    PositivityWitness,
    SelectionResult,
    StationaryProfile,
    WeightedPrincipalPart,
    infer_weight_from_exponent,
    tilted_simplex_problem,
)
from .face_selection_phase import (
    AffineWeightedDegree,
    FaceSelectionPhaseDiagram,
    MechanismQualification,
    ParametricFaceMechanism,
    ParametricFaceSelectionProblem,
    PhaseChamber,
    PhaseEvaluation,
    PhaseTransition,
    PhaseWall,
    weighted_degree_from_exponents,
)
from .ambient_face_compiler import (
    AmbientFaceCompilation,
    AmbientTermTransport,
    AmbientTransport,
    EdgeMonomialLineage,
    compile_ambient_face_selection,
    exact_chart_from_active_constraints,
    transport_ambient_polynomial,
)


def analyze_face_selection(payload, *, backend=None):
    """Lazy public entry point for the JSON-safe face-selection backend."""
    from .adjudication.polyhedra.backend import analyze_face_selection as _analyze

    return _analyze(payload, backend=backend)


def handle_face_selection_json(document, *, backend=None):
    """Lazy public entry point for one JSON request or batch."""
    from .adjudication.polyhedra.backend import handle_json as _handle

    return _handle(document, backend=backend)

__all__ = [
    "ConfusionScorer",
    "LEDGER",
    "Proposition",
    "Stance",
    "TurnScore",
    "detect_stance",
    "score_dialogue",
    "score_text",
    "DecompositionStabilityReport",
    "DecompositionStrategy",
    "DesignRulebook",
    "StabilityBounds",
    "AlgorithmStep",
    "NearOptimalProbe",
    "StructuralReason",
    "VertexProbeAlgorithm",
    "VertexProbeCertificate",
    "ExtremalSelectionResult",
    "FormalCoexponentialSpec",
    "SubstituteLimits",
    "SubstituteReport",
    "BlockFisher",
    "BlockLayout",
    "FactorizationAnalysis",
    "LeakageReport",
    "QuadraticJointObjective",
    "BlockAssignment",
    "ComponentwiseProbe",
    "CoupledProblem",
    "ParameterBlockSpec",
    "WorstCaseResult",
    "BoxBounds",
    "CompositeObjective",
    "HypersurfaceBox",
    "MaximizerResult",
    "Theta",
    "AdjunctionDirection",
    "ConceptualPolytope",
    "Vertex",
    "cardinality_obstruction",
    "curry_bijection",
    "exponential",
    "hom_cardinality",
    "left_adjoint_to_coproduct_exists",
    "maximize_under_coproduct_blocks",
    "NEIGHBOR_GUIDES",
    "NeighborVertex",
    "VertexGuide",
    "closed_monoidal_vs_cartesian",
    "demonstrate_neighbors",
    "duality_strategy_note",
    "walk_from_empty_coexponential",
    "box_theorem_summary",
    "demonstrate_box",
    "adversarial_theorem_summary",
    "default_hypersurface_problem",
    "demonstrate_adversarial",
    "build_block_fisher",
    "demonstrate_fisher_factorization",
    "factorization_summary",
    "nearly_optimal_when",
    "fisher_from_coupled_problem",
    "factorization_from_hypersurface",
    "evaluate_substitute",
    "extremal_selection_on_polytope",
    "demonstrate_substitute",
    "substitute_summary",
    "demonstrate_vertex_algorithm",
    "vertex_reduction_argument",
    "FisherPrunedVertexSearch",
    "NearOptimalProbeResult",
    "TheoremConstants",
    "certify_suboptimality",
    "epsilon_0_explicit",
    "theorem_constants_from_fisher",
    "CategoricalSetting",
    "Discovery",
    "EnrichmentWeights",
    "FiniteSite",
    "LawvereMetric",
    "LearnerSession",
    "LearnerTrajectoryLog",
    "TrajectoryStep",
    "compare_lawvere_vs_plain",
    "default_two_object_site",
    "sweep_site_exponentials",
    "LiveEpsilonReading",
    "SearchMode",
    "probe_setting",
    "recommend_search_mode",
    "run_research_discoveries",
    "compare_epsilon_unweighted_vs_enriched",
    "FormalStatement",
    "PROOF_REGISTRY",
    "formal_discoveries_markdown",
    "verify_all_proofs",
    "deliverables_manifest",
    "run_all_discoveries",
    "run_numerical_firsts",
    "write_discovery_artifacts",
    "assess_decomposition",
    "demonstrate_robustness",
    "robustness_sweep",
    "stability_framework_summary",
    "HypersurfacePlusInteraction",
    "NonlinearAnalysis",
    "NonlinearStudy",
    "demonstrate_nonlinear",
    "empirical_fisher_at",
    "vertex_maximize",
    "Monomial",
    "NewtonFace",
    "demonstrate_newton_tropical",
    "newton_tropical_face",
    "orthant_gap",
    "sharp_gap_constant",
    "sharp_single_axis_gap",
    "tropical_exponent",
    "tropical_gap_leading",
    "BasePower",
    "EdgeCoordinateChart",
    "FaceAnalysis",
    "FaceSelectionProblem",
    "FaceStatus",
    "HypothesisStatus",
    "InitialForm",
    "LawHypotheses",
    "PerturbationMonomial",
    "PolynomialPerturbation",
    "PositivityWitness",
    "SelectionResult",
    "StationaryProfile",
    "WeightedPrincipalPart",
    "infer_weight_from_exponent",
    "tilted_simplex_problem",
    "AffineWeightedDegree",
    "FaceSelectionPhaseDiagram",
    "MechanismQualification",
    "ParametricFaceMechanism",
    "ParametricFaceSelectionProblem",
    "PhaseChamber",
    "PhaseEvaluation",
    "PhaseTransition",
    "PhaseWall",
    "weighted_degree_from_exponents",
    "AmbientFaceCompilation",
    "AmbientTermTransport",
    "AmbientTransport",
    "EdgeMonomialLineage",
    "compile_ambient_face_selection",
    "exact_chart_from_active_constraints",
    "transport_ambient_polynomial",
    "analyze_face_selection",
    "handle_face_selection_json",
]
